ADDRESSES_LABEL = "Adresser"
FULL_ADDRESSES_LABEL = "FULL_Adresser"

ADDRESSES_DATA = [
    (
        "Vi bor på Lindesvägen 21, 26371 Jonstorp",
        {"entities": [(10, 40, FULL_ADDRESSES_LABEL)]},
    ),
    (
        "Folkbokföringen Lindesvägen 21 26371 Jonstorp",
        {"entities": [(16, 45, FULL_ADDRESSES_LABEL)]},
    ),
    (
        "Lindesvägen 21 Lindesvägen 21",
        {"entities": [(0, 14, ADDRESSES_LABEL), (15, 29, ADDRESSES_LABEL)]},
    ),
    (
        "Lindesvägen 21 ligger i Kullabygden I området finns många hus där rot- och rutavdraget används flitigt.",
        {"entities": [(0, 14, ADDRESSES_LABEL)]},
    ),
    (
        "Just nu finns 2 objekt till salu i Jonstorp Kärrsnäppevägen 10 , 3 rum & kök, 87½ m² 5 197 kr/mån 1 995 000 kr Revavägen 52 , 3 rum & kök, 82 m² 5 275 kr/mån 1 095 000 kr",
        {"entities": [(35, 62, ADDRESSES_LABEL)]},
    ),
    (
        "Bara sex minuters promenad bort ligger närmsta livsmedelsbutik, ICA Nära på Jonstorpsvägen 42.",
        {"entities": [(76, 93, ADDRESSES_LABEL)]},
    ),
    (
        "Min kompis är stadgad på Brommagatan 32, 254 38 Helsingborg. Trevligt va?",
        {"entities": [(24, 56, FULL_ADDRESSES_LABEL)]},
    ),
    (
        "120 kvadratmeter stort hus i Helsingborg sålt till nya ägare. 3 820 000 kronor fick Philip Troedsson och Charlene Cecilia Maria Holmström, båda 31 år, ge för huset på adressen Spireagatan 24 i Helsingborg. Huset är 120 kvadratmeter stort och byggdes 2004. Köpet från säljaren Sara Marika och Johan Westander blev klart i mars 2019. I våras såldes ett annat hus på samma gata, på Spireagatan 45. Där blev priset för den 160 kvadratmeter stora villan 3 745 000 kronor.",
        {"entities": [(176, 204, ADDRESSES_LABEL)]},
    ),
    (
        "ADRESS: BOX 420 34, 126 12 STOCKHOLM",
        {"entities": [(8, 36, FULL_ADDRESSES_LABEL)]},
    ),
    (
        "Jag känner Ulf. Han och hans fru bor i Helsingborg på Bunkalundsvägen 5. Hans son Ingvar har en lägenhet i Kalmar, på adress 391 00 Kalmar, Lorensbergsleden 1",
        {"entities": [(54, 71, ADDRESSES_LABEL), (125, 158, FULL_ADDRESSES_LABEL)]},
    ),
    (
        "Tittapå lägenhet Södra Stenbocksgatan 89",
        {"entities": [(17, 40, ADDRESSES_LABEL)]},
    ),
    (
        "Trodde det gällde  en lägenhet som blir ledig den 1/6 på Västra Hörrgatan 54.",
        {"entities": [(57, 77, ADDRESSES_LABEL)]},
    ),
    (
        "GleSYS AB Box 134, 311 22 Falkenberg, Sweden support@glesys.se +46-346-738 800",
        {"entities": [(10, 44, FULL_ADDRESSES_LABEL)]},
    ),
    (
        "Bor i Wilson Park i Helsingborg, 40 år. Direktörsgatan 27 25246 Helsingborg Lägenhetsnummer 1201.",
        {"entities": [(40, 75, FULL_ADDRESSES_LABEL)]},
    ),
    (
        "David och Sara Anklew, 33 och 32 år, har tagit över fastigheten på adressen Stengatan 20 i Helsingborg från Mikael Sjunnesson. Ägarbytet blev klart i maj 2019 och köpesumman blev 3 920 000 kronor. Byggår för huset är 1975 och boarean är 172 kvadratmeter. Bara några hundra meter bort såldes nyligen ett annat hus, på Runristargatan 21. Där såldes ett 124 kvadratmeter stort hus och priset för det blev 2 350 000 kronor.",
        {"entities": [(76, 88, ADDRESSES_LABEL), (317, 334, ADDRESSES_LABEL)]},
    ),
    (
        "Manoj Kumar Puthia, 47, och Anna Elisabeth Nyman, 36, från Hurva, har köpt huset på adressen Nordströms Sträde 9 i Båstad av säljaren Gunnar Paulsson Nyman. Köpesumman blev 4 375 000 kronor och de nya ägarna tog över huset i maj 2019. För mindre än en månad sedan såldes ett annat hus alldeles i närheten, på Christian Ii:S Väg 14A. Priset blev där 5 150 000 kronor, för det 135 kvadratmeter stora huset.",
        {"entities": [(93, 112, ADDRESSES_LABEL), (309, 331, ADDRESSES_LABEL)]},
    ),
    (
        "Marie Jinnemo, 32, och Victor Paulsson, 23, har köpt huset på Torgvägen 15 i Förslöv av säljaren Fritz Gösta och Fredrik Gebauer. Köpesumman blev 1 975 000 kronor och de nya ägarna tog över huset i april 2019. Huset är 95 kvadratmeter stort och byggdes 1929. Precis i närheten såldes i våras ett annat hus, på Mejerivägen 2. Där landade priset på 900 000 kronor för det 150 kvadratmeter stora huset.",
        {"entities": [(62, 74, ADDRESSES_LABEL), (310, 323, ADDRESSES_LABEL)]},
    ),
    (
        "Försäljningen av fastigheten på Odengatan 1 i Åstorp är nu klar. Nya ägare är Jennie Bengtsson, 32, och Johan Andersson, 36, och säljare är Johan André Björkman och Ida Johanna Marie Björkman. Huset byggdes 1952 och har en boyta på 95 kvadratmeter. Ägarbytet blev klart i april 2019 och priset blev 1 750 000 kronor. I januari såldes ett annat hus på samma gata, på Odengatan 12. Där blev priset för den 90 kvadratmeter stora villan 1 655 000 kronor.",
        {"entities": [(32, 43, ADDRESSES_LABEL), (366, 378, ADDRESSES_LABEL)]},
    ),
    (
        "Försäljningen av fastigheten på Rosendalsgatan 6 i Åstorp är nu klar. Nya ägare är Vian Farhood, 26, och Ameen Haider Kadhim Kadhim, 30, och säljare är Alexandra och Alexander Persson. Det 169 kvadratmeter stora huset är byggt 1969. Ägarbytet blev klart i april 2019 och priset blev 2 000 000 kronor. Lite mindre än en kilometer därifrån såldes för mindre än en månad sedan ett annat hus, på Bjärshögsgatan 82. Även där landade priset på 2 000 000 kronor.",
        {"entities": [(32, 48, ADDRESSES_LABEL), (392, 409, ADDRESSES_LABEL)]},
    ),
    (
        "I området kring Tärnvägen 4 bor många i villor och flerbostadshus som för det mesta är byggda på 30- och 70-talet.",
        {"entities": [(16, 27, ADDRESSES_LABEL)]},
    ),
    (
        "Gatuadress Lindesvägen 21 Postnummer 26371 Postort JONSTORP",
        {"entities": [(11, 42, ADDRESSES_LABEL)]},
    ),
    (
        "Bråkmakargatan 5 har sålts. Är du nyfiken på vad slutpriset blev?",
        {"entities": [(0, 16, ADDRESSES_LABEL)]},
    ),
    (
        "Dom gav mig din adress på Gatan 1, Laxå",
        {"entities": [(26, 39, ADDRESSES_LABEL)]},
    ),
    ("Barbro Rudolfsson bor på Tennisvägen 2, 28537 Markaryd", {"entities": [(25, 54, FULL_ADDRESSES_LABEL)]}),
    ("Gustav Johnsson bor på Mårtenstorpsgatan 93 lgh 0025, 25667 Helsingborg",
     {"entities": [(23, 71, FULL_ADDRESSES_LABEL)]}),
    ("Malin Berndtsson bor på Andersgårdsvägen 6, 51931 Horred",
     {"entities": [(24, 56, FULL_ADDRESSES_LABEL)]}),
    ("Sussi	Hellberg bor på Kärrgatan 2, 24334 Höör", {"entities": [(22, 45, FULL_ADDRESSES_LABEL)]}),
    ("Jonas	Pettersson bor på Olasgård Olofsberg 481, 30564 Gullbrandstorp",
     {"entities": [(24, 66, FULL_ADDRESSES_LABEL)]}),
    ("Sofie Anefors bor på Gertruds gata 26, 42167 Västra Frölunda", {"entities": [(21, 60, FULL_ADDRESSES_LABEL)]}),
    ("Sara Nilsson bor på Mårnarp 1358, 28265 Bjärnum", {"entities": [(20, 47, FULL_ADDRESSES_LABEL)]}),
    ("Anders Bergvall bor på Bondevägen 10, 35253 Växjö", {"entities": [(23, 49, FULL_ADDRESSES_LABEL)]}),
    (
        "Snickare Totalentrepenad Fönstermontering rut RUT-tjänster : Flytthjälp Trädfällning Trädgårdshjälp rot Ytan räknas :",
        {"entities": []},
    ),
    (
        "Visa mer Musical Highlights Vol. 13 Jarl Kulle Scenen 2020 M02 20 Visa mer FRÅN BROADWAY TILL DUVEMÅLA",
        {"entities": []}
    ),
    (
        "Bostadsmarknaden i Kullabygden 12 objekt till salu i området Just nu finns 12 objekt till salu i Jonstorp Nära Bad och Hav",
        {"entities": []}
    ),
    (
        "Störst är Eriks Fönsterputs i Sverige ADRESSER AB som 2017 omsatte 46,7 miljoner kr.",
        {"entities": []}
    ),
    ("Pyjamas  50%", {"entities": []}),
    ("62%", {"entities": []}),
    ("Pojkar 17, grupp A", {"entities": []}),
    ("41 00 Kontakt", {"entities": []}),
    ("reg.grupp 2   SM Futsal,", {"entities": []}),
    ("Grupp 2,", {"entities": []}),
    ("Biter dem?", {"entities": []}),
    ("042-36 78 48", {"entities": []}),
    ("08-20 88 64", {"entities": []}),
    ("Det är synd om kungafamiljen..", {"entities": []}),
    ("Det är inga problem om det är kallt, så länge det är soligt.", {"entities": []}),
    ("Jag gillar Systembolaget.", {"entities": []}),
    ("Nån gång vill jag bo på landet igen.", {"entities": []}),
    ("Jag har inte läst Milleniumtrilogin.", {"entities": []}),
    ("Facebook äger alla dina bilder..", {"entities": []}),
    ("Jag äter inte mycket kött..", {"entities": []}),
    ("Det har redan snöat i Norrland.", {"entities": []}),
    ("Jag har läst tyska i skolan, men jag kan ingenting.", {"entities": []}),
    ("Jag går till folktandvården.", {"entities": []}),
    ("Det är svenska jordgubbar.", {"entities": []}),
    ("Jag lyssnar bara på P1.", {"entities": []}),
    ("Så gör man på kontinenten.", {"entities": []}),
    ("Med helkaklat badrum.", {"entities": []}),
    ("Det är så tomt för att det är helgen innan löning.", {"entities": []}),
    ("Jag gillar finlandssvenska.", {"entities": []}),
    ("Vad är egentligen det nya Söder?", {"entities": []}),
    ("Jag handlar inte på Lidl.", {"entities": []}),
    ("Det går tyvärr inte att bara beställa pannkakor.", {"entities": []}),
    ("Antingen är de för hårda eller övermogna.", {"entities": []}),
    ("Vi kan sätta oss i finrummet.", {"entities": []}),
    ("Jag känner jättemånga som har träffats på nätet.", {"entities": []}),
    ("Vad fick du betala för din lägenhet?", {"entities": []}),
    ("Den bästa falafeln finns i Malmö.", {"entities": []}),
    ("Mina päron kommer på besök.", {"entities": []}),
    ("De har en jättebra restaurang på Fotografiska.", {"entities": []}),
    ("Vad är det för trä?", {"entities": []}),
    ("Den kan vi ha i sommarstugan.", {"entities": []}),
    ("Vi vill inte veta vad det blir.", {"entities": []}),
    ("Vi är inte ihop.", {"entities": []}),
    ("Varför har du inte pluggat till läkare?", {"entities": []}),
    ("Håkan är så bra.", {"entities": []}),
    ("Finns det på SVT Play?", {"entities": []}),
    ("Det är helt sjukt att det är billigare att flyga.", {"entities": []}),
    ("Harald Berglin (1875-1925) ritade fyravåningshuset, med inredd vindsvåning, uppfört mellan 1902 och 1904. ",
     {"entities": []}),
    ("Huset uppfördes av staden mellan 1892 och1897 efter Alfred Hellerströms (1863- 1931) ritningar.",
     {"entities": []}),
    (
        "Tävlingen vanns av Alfred Hellerström, som nyss utexaminerats från konstakademien i Stockholm.",
        {"entities": []}),
    ("Bara hans adress, Fältgatan 6	26139 Landskrona", {"entities": [(18, 47, FULL_ADDRESSES_LABEL)]}),
    ("Han hade en adress. Humlevägen 10	24441 Kävlinge", {"entities": [(20, 47, FULL_ADDRESSES_LABEL)]}),
    ("Ge mig din adress. Sven svarade: Kastanjevägen 6	23437 Lomma", {"entities": [(33, 60, FULL_ADDRESSES_LABEL)]}),
    ("Kontor Bygatan 24 B 28023 Hästveda", {"entities": [(7, 34, FULL_ADDRESSES_LABEL)]}),
    ("Han nämnde en adress, Skanslyckan 40 43973 Fjärås.", {"entities": [(22, 49, FULL_ADDRESSES_LABEL)]}),
    ("Adressen Majsgatan 24 var på landet.", {"entities": [(9, 21, ADDRESSES_LABEL)]}),
    ("Då ska jag be om din adress. Svaret var Ängslyckegatan 5", {"entities": [(40, 56, ADDRESSES_LABEL)]}),
    ("Hugo gav mig langarens adress, Danielslundsgatan 34.", {"entities": [(31, 51, ADDRESSES_LABEL)]}),
    ("Ett besök på deras gammla adress Trulsibrunnvägen 20 E 23638 Höllviken.",
     {"entities": [(33, 70, FULL_ADDRESSES_LABEL)]}),
    ("En adress Abborrvägen 8 var han?.", {"entities": [(10, 23, ADDRESSES_LABEL)]}),
    ("Dessutom hade en adress lagts till. Högestadsgatan 51", {"entities": [(36, 53, ADDRESSES_LABEL)]}),
    ("Han gick vidare till Ibrahims adress, Valinge Bönarp 20, 43292 Varberg",
     {"entities": [(38, 70, FULL_ADDRESSES_LABEL)]}),
    ("Adressen Barsebäcksvägen 50 24630 Löddeköpinge var hemlig och så också telefonnumret.",
     {"entities": [(9, 37, FULL_ADDRESSES_LABEL)]}),
    ("Du menar Bjäredsvägen 342?", {"entities": [(9, 26, ADDRESSES_LABEL)]}),
    ("Har du nån känd adress på honom? Ja, Jordatalsvägen 1", {"entities": [(37, 53, ADDRESSES_LABEL)]}),
    ("Vi letade länge innan vi fann rätt adress. Valhallsvägen 64, 26261 Ängelholm",
     {"entities": [(43, 76, FULL_ADDRESSES_LABEL)]}),
    ("Känner mig stolt över att ha en adress här på Södervångsvägen 139.", {"entities": [(46, 65, ADDRESSES_LABEL)]}),
    ("PET’s dyra adress Ekbackegatan 14.", {"entities": [(18, 33, ADDRESSES_LABEL)]}),
    ("24 år januari", {"entities": []})
]
