LIST = ["https://www.hitta.se/william+myllenberg/jonstorp/person/iLzxWWRP2Z",
        "https://www.hitta.se/adrian+wallenholm/strandbaden/person/zTlZvvOkko",
        "https://helsingborg.se/uppleva-och-gora/turistinformation/",
        "https://www.vastsverige.com/alingsas/alingsas-turistbyra/",
        "https://www.destinationuppsala.se/sv/Destination-Uppsala/turistinformation/",
        "http://www.svalov.se/uppleva--gora/turism/rostanga-turistinformation.html",
        "http://www.almhult.se/visitalmhult/sv/turistinformation.4.72d0c2a614081ed78de3feb.html",
        "https://www.jonkoping.se/upplevagora/turistinformationochinfopointsforbesokare",
        "https://www.visitfilipstad.se/sv/filipstads-turistinformation",
        "https://www.malmocity.se/turistinformation/",
        "https://www.visithagfors.se/sv/turistinformationen",
        "http://www.gnosjo.se/upplevagora/turistinformation.4.2e94ea361341992822c80001188.html",
        "https://www.varberg.se/upplevagora/turistinformation.4.2fd3f9113e650a5ee4174b.html",
        "https://www.visittorsby.se/sv/turistbyra",
        "https://www.visitarvika.se/sv/arvika-turistbyra/arvika-turistbyra",
        "https://sv.wikipedia.org/wiki/Postnummer",
        "https://sv.wikipedia.org/wiki/Adress",
        "https://www.sida.se/Svenska/Kontakta-oss/kontakta-oss/",
        "https://jobbasmart.com/",
        "http://fixarna.it/",
        "https://eriksfonsterputs.se/",
        "https://eila.se/",
        "https://liviadeak.se/kontakt/",
        "http://www.hif.se/",
        "https://www.mff.se/",
        "https://fogis.se/",
        "http://www.skaneboll.se/",
        "https://fragbite.se/",
        "https://www.hd.se",
        "https://www.sydsvenskan.se/",
        "https://www.svenskalag.se/jonstorp/kontakt",
        "https://jetshop.se/flight/",
        "https://www.nike.com/se/help",
        "https://min.linasmatkasse.se/"
        ]


DISPLACY_LIST = ["https://www.jonkoping.se/upplevagora/turistinformationochinfopointsforbesokare"]
